openapi: 3.0.3
info:
    title: Features API
    description: Api to manage the features of the site
    version: 1.0.1

paths:
    /api/features:
        get:
            tags:
                - features
            description: Returns all the features of the site from de database
            summary: Returns all the features of the site from de database
            operationId: features
            parameters:
                - $ref: "#/components/parameters/access_token"
            responses:
                200:
                    description: OK
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/FeatureDto'
                401:
                    description: Access token not valid
            deprecated: false
        post:
            tags:
                - features
            description: Update the feature of the site inside de database
            summary: Update the feature of the site inside de database
            operationId: update-features
            parameters:
                - $ref: "#/components/parameters/access_token"
                - name: feature
                  in: query
                  required: true
                  description: The feature to change status
                  schema:
                      type: string
                      minLength: 7
                      pattern: "[a-zA-Z]"
                      example: clanWar

            responses:
                200:
                    description: OK
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/FeatureDto'
                400:
                    description: Bad request (access_token or feature not given) or feature given does not exist
                401:
                    description: Access token not valid
            deprecated: false

components:
    parameters:
        access_token:
            in: query
            description: The wot access token of the user
            required: true
            name: access_token
            schema:
                type: string
                minLength: 40
                maxLength: 40
                pattern: "[a-f0-9]{40}"
    schemas:
        FeatureDto:
            title: FeatureDto
            description: The representation of all features of the site
            type: object
            properties:
                clanWar:
                    type: boolean
                    description: If the clan war tab is enabled
                    example: true
        FeatureEnum:
            title: FeatureEnum
            type: string
            enum:
                - clanWar