openapi: 3.0.3
info:
    title: Feature API
    description: Api to fetch the features of the site
    version: 1.0.0

paths:
    /api/features:
        get:
            tags:
                - features
            description: Returns all the features of the site from de database
            summary: Returns all the features of the site from de database
            operationId: features
            parameters:
                - name: access_token
                  in: query
                  description: The wot access token of the user
                  required: true
                  schema:
                      type: string
                      minLength: 40
                      maxLength: 40
                      pattern: "[a-e0-9]{40}"
            responses:
                200:
                    description: OK
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/FeatureDto'
                401:
                    description: Access token not valid
            deprecated: false

components:
    schemas:
        FeatureDto:
            title: FeatureDto
            type: object
            properties:
                clanWar:
                    type: boolean
                    description: Si l'onglet clan war est activé
                    example: true
        FeatureEnum:
            title: FeatureEnum
            type: string
            enum:
                - clanWar