name: Update release version
on:
  push:
    tags:
      - "*.*.*"

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
      - name: Install Java and Maven
        uses: actions/setup-java@v1
        with:
          java-version: 20
      - name: Set output
        id: vars
        run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT
      - if: github.event.release
        name: Update version in pom.xml
        env:
          RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
        run: |
          echo $RELEASE_VERSION
          echo ${{ steps.vars.outputs.tag }}
          mvn -B versions:set -DnewVersion=${{ steps.vars.outputs.tag }} -DgenerateBackupPoms=false
