name: Update release version
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Latest Commit
        uses: actions/checkout@v2
      - name: Bump Version
        id: bump
        uses: nnichols/maven-version-bump-action@v4
        with:
          github-token: ${{ secrets.TOKEN }}
      - name: Push version
        run: |
          git push --tags https://${{ secrets.TOKEN }}@github.com/${{ github.repository }} main
      - name: Print Version
        run: "echo 'New Version: ${{steps.bump.outputs.version}}'"